# Generated by Django 5.2 on 2025-04-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbandata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='KanbanTask',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
