# Generated by Django 5.2 on 2025-04-10 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbandata', '0002_bookreview_delete_kanbantask_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('todo', 'К выполнению'), ('in_progress', 'В работе'), ('done', 'Готово')], default='todo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершен'), ('on_hold', 'На паузе')], default='active', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='BookReview',
        ),
        migrations.AddField(
            model_name='kanbantask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kanbandata.project'),
        ),
    ]
